[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "https://www.mftravel.co.uk/*"
  to = "https://mftravel.co.uk/:splat"
  status = 301
  force = true
